name: example jobs

on: 
  push

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
      - name: exec command
        run: echo "Hello, World from job1!"

  job2:
    runs-on: ubuntu-latest
    steps: 
      - name: exec command
        run: echo "Hello, World from job2!"          