name: example jobs

on: 
  workflow_dispatch

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: create artifact
        run: echo "Featured artifacts (changed)" > build-result.txt
      - uses: actions/upload-artifact@v2
        with: 
          name: build-result
          path: build-result.txt

  deploy:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/download-artifact@v2
        with: 
          name: build-result
          path: build-result.txt

      - name: read artifact
        run: ls build-result.txt